export const SETTINGS = {
  WIDTH: 600,
  HEIGHT: 400,
  PLAYER: {
    WIDTH: 20,
    HEIGHT: 80,
    GAP: 10,
  },
  BALL: {
    WIDTH: 15,
    HEIGHT: 15,
    SPEED_FAST: 3,
    SPEED_MEDIUM: 2,
    SPEED_SLOW: 1.5,
  },
  COUNTDOWN_SEC: 5,
  COUNTDOWN_SIZE: 40,
};

export const CLIENT_SETTINGS = {
  WIDTH: SETTINGS.WIDTH,
  HEIGHT: SETTINGS.HEIGHT,
};
