import { UserStatus } from 'src/entities/User';

const userInitData = [
  {
    email: 'temp1@temp.com',
    nickname: 'temp1',
    intraUsername: 'temp_intra_1',
    imagePath: 'https://picsum.photos/id/10/500/500',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp2@temp.com',
    nickname: 'temp2',
    intraUsername: 'temp_intra_2',
    imagePath: 'https://picsum.photos/id/100/500/500',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp3@temp.com',
    nickname: 'temp3',
    intraUsername: 'temp_intra_3',
    imagePath: 'https://picsum.photos/id/1000/500/500',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp4@temp.com',
    nickname: 'temp4',
    intraUsername: 'temp_intra_4',
    imagePath: 'https://picsum.photos/id/1002/500/500',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp5@temp.com',
    nickname: 'temp5',
    intraUsername: 'temp_intra_5',
    imagePath: 'https://picsum.photos/id/1003/500/500',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp6@temp.com',
    nickname: 'temp6',
    intraUsername: 'temp_intra_6',
    imagePath: 'https://picsum.photos/id/1004/500/500',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp7@temp.com',
    nickname: 'temp7',
    intraUsername: 'temp_intra_7',
    imagePath: 'https://picsum.photos/id/101/500/500',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp8@temp.com',
    nickname: 'temp8',
    intraUsername: 'temp_intra_8',
    imagePath: 'https://picsum.photos/id/1018/500/500',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp9@temp.com',
    nickname: 'temp9',
    intraUsername: 'temp_intra_9',
    imagePath: 'https://picsum.photos/id/1019/500/500',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp10@temp.com',
    nickname: 'temp10',
    intraUsername: 'temp_intra_10',
    imagePath: 'https://picsum.photos/id/1022/500/500',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
];

export { userInitData };
