import { UserStatus } from 'src/entities/User';

const userInitData = [
  {
    email: 'temp1@temp.com',
    nickname: '예시_1',
    intraUsername: 'temp_intra_1',
    imagePath: 'temp_path_1',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp2@temp.com',
    nickname: '예시_2',
    intraUsername: 'temp_intra_2',
    imagePath: 'temp_path_2',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp3@temp.com',
    nickname: '예시_3',
    intraUsername: 'temp_intra_3',
    imagePath: 'temp_path_3',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp4@temp.com',
    nickname: '예시_4',
    intraUsername: 'temp_intra_4',
    imagePath: 'temp_path_4',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp5@temp.com',
    nickname: '예시_5',
    intraUsername: 'temp_intra_5',
    imagePath: 'temp_path_5',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp6@temp.com',
    nickname: '예시_6',
    intraUsername: 'temp_intra_6',
    imagePath: 'temp_path_6',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp7@temp.com',
    nickname: '예시_7',
    intraUsername: 'temp_intra_7',
    imagePath: 'temp_path_7',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp8@temp.com',
    nickname: '예시_8',
    intraUsername: 'temp_intra_8',
    imagePath: 'temp_path_8',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp9@temp.com',
    nickname: '예시_9',
    intraUsername: 'temp_intra_9',
    imagePath: 'temp_path_9',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp10@temp.com',
    nickname: '예시_10',
    intraUsername: 'temp_intra_10',
    imagePath: 'temp_path_10',
    status: UserStatus.OFFLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
];

export { userInitData };
