import { UserStatus } from 'src/entities/User';

const userInitData = [
  {
    email: 'temp1@temp.com',
    nickname: 'temp1',
    intraUsername: 'temp_intra_1',
    imagePath: 'https://picsum.photos/id/10/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp2@temp.com',
    nickname: 'temp2',
    intraUsername: 'temp_intra_2',
    imagePath: 'https://picsum.photos/id/100/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp3@temp.com',
    nickname: 'temp3',
    intraUsername: 'temp_intra_3',
    imagePath: 'https://picsum.photos/id/1000/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp4@temp.com',
    nickname: 'temp4',
    intraUsername: 'temp_intra_4',
    imagePath: 'https://picsum.photos/id/1002/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp5@temp.com',
    nickname: 'temp5',
    intraUsername: 'temp_intra_5',
    imagePath: 'https://picsum.photos/id/1003/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp6@temp.com',
    nickname: 'temp6',
    intraUsername: 'temp_intra_6',
    imagePath: 'https://picsum.photos/id/1004/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp7@temp.com',
    nickname: 'temp7',
    intraUsername: 'temp_intra_7',
    imagePath: 'https://picsum.photos/id/101/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp8@temp.com',
    nickname: 'temp8',
    intraUsername: 'temp_intra_8',
    imagePath: 'https://picsum.photos/id/1018/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp9@temp.com',
    nickname: 'temp9',
    intraUsername: 'temp_intra_9',
    imagePath: 'https://picsum.photos/id/1019/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp10@temp.com',
    nickname: 'temp10',
    intraUsername: 'temp_intra_10',
    imagePath: 'https://picsum.photos/id/1022/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp11@temp.com',
    nickname: 'temp11',
    intraUsername: 'temp_intra_11',
    imagePath: 'https://picsum.photos/id/1023/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp12@temp.com',
    nickname: 'temp12',
    intraUsername: 'temp_intra_12',
    imagePath: 'https://picsum.photos/id/1024/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp13@temp.com',
    nickname: 'temp13',
    intraUsername: 'temp_intra_13',
    imagePath: 'https://picsum.photos/id/1025/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp14@temp.com',
    nickname: 'temp14',
    intraUsername: 'temp_intra_14',
    imagePath: 'https://picsum.photos/id/1026/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp15@temp.com',
    nickname: 'temp15',
    intraUsername: 'temp_intra_15',
    imagePath: 'https://picsum.photos/id/1027/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp16@temp.com',
    nickname: 'temp16',
    intraUsername: 'temp_intra_16',
    imagePath: 'https://picsum.photos/id/1028/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp17@temp.com',
    nickname: 'temp17',
    intraUsername: 'temp_intra_17',
    imagePath: 'https://picsum.photos/id/1029/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp18@temp.com',
    nickname: 'temp18',
    intraUsername: 'temp_intra_18',
    imagePath: 'https://picsum.photos/id/1030/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
  {
    email: 'temp19@temp.com',
    nickname: 'temp19',
    intraUsername: 'temp_intra_19',
    imagePath: 'https://picsum.photos/id/1031/500/500',
    status: UserStatus.ONLINE,
    banDate: null,
    experience: 0,
    rankId: 1,
  },
];

export { userInitData };
