#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Pre-push Hook: Checking branch name / Mengecek nama branch..."

BRANCH=`git rev-parse --abbrev-ref HEAD`

if [ "$BRANCH" = main ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi


echo ">> Finish checking branch name / Selesai mengecek nama branch.\n==="

exit 0
